# Generated by Django 5.0.14 on 2026-05-09 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('qa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionactivity',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='questionactivity',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='questionactivity',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('no_answer', 'No Relevant Info'), ('error', 'Error')], default='success', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='questionactivity',
            index=models.Index(fields=['user', '-created_at'], name='qa_question_user_id_f09c41_idx'),
        ),
        migrations.AddIndex(
            model_name='questionactivity',
            index=models.Index(fields=['document', 'user'], name='qa_question_documen_1d1a67_idx'),
        ),
    ]
