# Generated by Django 5.0.14 on 2026-05-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_alter_questionactivity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionactivity',
            name='task_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
