# Generated by Django 5.0.14 on 2026-05-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'XLSX'), ('xls', 'XLS'), ('txt', 'TXT'), ('csv', 'CSV')], max_length=4),
        ),
    ]
